/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnetikCloud);
  }
}(this, function(expect, KnetikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnetikCloud.OAuth2ProviderResource();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OAuth2ProviderResource', function() {
    it('should create an instance of OAuth2ProviderResource', function() {
      // uncomment below and update the code to test OAuth2ProviderResource
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be.a(KnetikCloud.OAuth2ProviderResource);
    });

    it('should have the property authorizationGrantType (base name: "authorization_grant_type")', function() {
      // uncomment below and update the code to test the property authorizationGrantType
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property authorizationUri (base name: "authorization_uri")', function() {
      // uncomment below and update the code to test the property authorizationUri
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property clientAuthenticationMethod (base name: "client_authentication_method")', function() {
      // uncomment below and update the code to test the property clientAuthenticationMethod
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "client_id")', function() {
      // uncomment below and update the code to test the property clientId
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property clientName (base name: "client_name")', function() {
      // uncomment below and update the code to test the property clientName
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property clientSecret (base name: "client_secret")', function() {
      // uncomment below and update the code to test the property clientSecret
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property jwkSetUri (base name: "jwk_set_uri")', function() {
      // uncomment below and update the code to test the property jwkSetUri
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property oidcCompliant (base name: "oidc_compliant")', function() {
      // uncomment below and update the code to test the property oidcCompliant
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property providerDetails (base name: "provider_details")', function() {
      // uncomment below and update the code to test the property providerDetails
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property providerId (base name: "provider_id")', function() {
      // uncomment below and update the code to test the property providerId
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property scopes (base name: "scopes")', function() {
      // uncomment below and update the code to test the property scopes
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property tokenUri (base name: "token_uri")', function() {
      // uncomment below and update the code to test the property tokenUri
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property userInfoEndpointUri (base name: "user_info_endpoint_uri")', function() {
      // uncomment below and update the code to test the property userInfoEndpointUri
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

    it('should have the property userInfoEndpointUserNameAttributeName (base name: "user_info_endpoint_user_name_attribute_name")', function() {
      // uncomment below and update the code to test the property userInfoEndpointUserNameAttributeName
      //var instane = new KnetikCloud.OAuth2ProviderResource();
      //expect(instance).to.be();
    });

  });

}));
