/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnetikCloud);
  }
}(this, function(expect, KnetikCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnetikCloud.VerificationRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VerificationRequest', function() {
    it('should create an instance of VerificationRequest', function() {
      // uncomment below and update the code to test VerificationRequest
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be.a(KnetikCloud.VerificationRequest);
    });

    it('should have the property additionalProperties (base name: "additional_properties")', function() {
      // uncomment below and update the code to test the property additionalProperties
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property codelength (base name: "codelength")', function() {
      // uncomment below and update the code to test the property codelength
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property createdDate (base name: "created_date")', function() {
      // uncomment below and update the code to test the property createdDate
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property expirationDate (base name: "expiration_date")', function() {
      // uncomment below and update the code to test the property expirationDate
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeNumbers (base name: "include_numbers")', function() {
      // uncomment below and update the code to test the property includeNumbers
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property originator (base name: "originator")', function() {
      // uncomment below and update the code to test the property originator
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property targetUser (base name: "target_user")', function() {
      // uncomment below and update the code to test the property targetUser
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property updatedDate (base name: "updated_date")', function() {
      // uncomment below and update the code to test the property updatedDate
      //var instane = new KnetikCloud.VerificationRequest();
      //expect(instance).to.be();
    });

  });

}));
